services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=Broker:redis:6379:0,CeleryResults:redis:6379:1,APICache:redis:6379:2

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI